# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks
import wagtailstreamfieldforms.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateField(verbose_name='Post Date')),
                ('body', wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='heading')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('singlelinefield', wagtail.wagtailcore.blocks.StructBlock((('label', wagtail.wagtailcore.blocks.CharBlock()), ('required', wagtail.wagtailcore.blocks.BooleanBlock(default=False, required=False)), ('help_text', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('default_value', wagtail.wagtailcore.blocks.CharBlock(required=False))))), ('multilinefield', wagtail.wagtailcore.blocks.StructBlock((('label', wagtail.wagtailcore.blocks.CharBlock()), ('required', wagtail.wagtailcore.blocks.BooleanBlock(default=False, required=False)), ('help_text', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('default_value', wagtail.wagtailcore.blocks.CharBlock(required=False))))), ('numberfield', wagtail.wagtailcore.blocks.StructBlock((('label', wagtail.wagtailcore.blocks.CharBlock()), ('required', wagtail.wagtailcore.blocks.BooleanBlock(default=False, required=False)), ('help_text', wagtail.wagtailcore.blocks.CharBlock(required=False))))), ('emailfield', wagtail.wagtailcore.blocks.StructBlock((('label', wagtail.wagtailcore.blocks.CharBlock()), ('required', wagtail.wagtailcore.blocks.BooleanBlock(default=False, required=False)), ('help_text', wagtail.wagtailcore.blocks.CharBlock(required=False))))), ('urlfield', wagtail.wagtailcore.blocks.StructBlock((('label', wagtail.wagtailcore.blocks.CharBlock()), ('required', wagtail.wagtailcore.blocks.BooleanBlock(default=False, required=False)), ('help_text', wagtail.wagtailcore.blocks.CharBlock(required=False))))), ('checkboxfield', wagtail.wagtailcore.blocks.StructBlock((('label', wagtail.wagtailcore.blocks.CharBlock()), ('required', wagtail.wagtailcore.blocks.BooleanBlock(default=False, required=False)), ('help_text', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('default_checked', wagtail.wagtailcore.blocks.BooleanBlock(default=False, required=False))))), ('dropdownfield', wagtail.wagtailcore.blocks.StructBlock((('label', wagtail.wagtailcore.blocks.CharBlock()), ('required', wagtail.wagtailcore.blocks.BooleanBlock(default=False, required=False)), ('help_text', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('choices', wagtail.wagtailcore.blocks.ListBlock(wagtailstreamfieldforms.blocks.FieldChoiceBlock)), ('allow_multiple_selections', wagtail.wagtailcore.blocks.BooleanBlock(default=False, required=False))))), ('radiofield', wagtail.wagtailcore.blocks.StructBlock((('label', wagtail.wagtailcore.blocks.CharBlock()), ('required', wagtail.wagtailcore.blocks.BooleanBlock(default=False, required=False)), ('help_text', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('choices', wagtail.wagtailcore.blocks.ListBlock(wagtailstreamfieldforms.blocks.FieldChoiceBlock))))), ('datefield', wagtail.wagtailcore.blocks.StructBlock((('label', wagtail.wagtailcore.blocks.CharBlock()), ('required', wagtail.wagtailcore.blocks.BooleanBlock(default=False, required=False)), ('help_text', wagtail.wagtailcore.blocks.CharBlock(required=False))))), ('datetimefield', wagtail.wagtailcore.blocks.StructBlock((('label', wagtail.wagtailcore.blocks.CharBlock()), ('required', wagtail.wagtailcore.blocks.BooleanBlock(default=False, required=False)), ('help_text', wagtail.wagtailcore.blocks.CharBlock(required=False)))))))),
                ('submit_label', models.CharField(default='Submit', max_length=255)),
                ('submitted_body', wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='heading')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock())))),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
